### ISSUE TITLE
NPM install error "Could not resolve dependency"

### ISSUE THREAD

**Issue by asplunds** [mbixby/react-advanced-click-away#1]
![image](https://user-images.githubusercontent.com/71442467/205050634-3d8bee93-970d-4502-9b5e-e905b237b014.png)

My React versions:
```json
"react": "^18.2.0",
"react-dom": "^18.2.0",
```

Would be awesome if you could fix this since I'm not willing to use `--force` or `--force-peer-dependencies`.

**Comment by mbixby** [comment]
Thanks for raising the issue, React 18 is in peer deps as of `v2.1.7`.
